// ============================================================
//  MAGICAL ATHLETE — Card Deck
//
//  This is the ONLY file you need to touch to change cards.
//
//  Each card looks like:
//    { id: 'tortoise',            unique, lowercase, no spaces
//      name: 'Tortoise',          shown on the card
//      emoji: '🐢',               the racer's pawn on the board
//      tag: 'Slow and steady',    little tagline under the name
//      text: 'Rule text…',        the ability, written plainly
//      pawns: 2 }                 OPTIONAL — racers with 2 pawns
//
//  ⚠ OFFICIAL SET: written from memory, not copied from the box.
//    Check each ability against your physical cards and fix
//    the text here. Only the "text" field matters for play.
// ============================================================

const OFFICIAL_CARDS = [
  { id: 'alchemist',    name: 'Alchemist',    emoji: '⚗️', tag: 'Turns ones into sixes',
    text: 'After you roll, you may flip the die to its opposite face (1↔6, 2↔5, 3↔4).' },
  { id: 'arithmancer',  name: 'Arithmancer',  emoji: '🔢', tag: 'Does the math',
    text: 'Roll two dice and move the difference between them. If you roll doubles, move 6.' },
  { id: 'assassin',     name: 'Assassin',     emoji: '🗡️', tag: 'Nothing personal',
    text: 'Whenever you land on a space with another racer, send that racer back to Start.' },
  { id: 'bomber',       name: 'Bomber',       emoji: '💣', tag: 'Fire in the hole',
    text: 'Once per race, instead of rolling, BLAST: every other racer within 3 spaces of you moves back 3.' },
  { id: 'centaur',      name: 'Centaur',      emoji: '🐎', tag: 'Half horse, all hustle',
    text: 'Roll two dice and use the higher result.' },
  { id: 'coach',        name: 'Coach',        emoji: '📣', tag: 'Everybody hustle!',
    text: 'At the start of your turn, every other racer on your space moves forward 2. Then roll as normal.' },
  { id: 'copycat',      name: 'Copycat',      emoji: '🐱', tag: 'Anything you can do',
    text: 'At the start of each of your turns, choose any other racer in this race. Use their ability this turn.' },
  { id: 'cupid',        name: 'Cupid',        emoji: '💘', tag: 'Hopelessly attached',
    text: 'At the start of the race, choose a rival. Whenever that rival moves forward, you also move forward 1.' },
  { id: 'dog',          name: 'Dog',          emoji: '🐕', tag: 'Who\'s a good racer?',
    text: 'Whenever another racer passes you, chase them: move forward 2.' },
  { id: 'gambler',      name: 'Gambler',      emoji: '🎲', tag: 'Double or nothing',
    text: 'After rolling, you may roll again — but you must use the second result.' },
  { id: 'genie',        name: 'Genie',        emoji: '🧞', tag: 'Your wish, granted',
    text: 'Once per race, instead of rolling, move directly to the space of any other racer.' },
  { id: 'ghost',        name: 'Ghost',        emoji: '👻', tag: 'Can\'t touch this',
    text: 'Other racers\' abilities cannot affect you.' },
  { id: 'golem',        name: 'Golem',        emoji: '🗿', tag: 'Slow, steady, stony',
    text: 'Rolls of 1, 2 or 3 count as 3. Rolls of 4, 5 or 6 count as 4.' },
  { id: 'hare',         name: 'Hare',         emoji: '🐇', tag: 'Fast asleep',
    text: 'Roll two dice and move the total. If you roll doubles, you take a nap: do not move.' },
  { id: 'hulk',         name: 'Hulk',         emoji: '💪', tag: 'Hulk throw!',
    text: 'Whenever you land on a space with other racers, throw them: each one moves back a number of spaces equal to your roll.' },
  { id: 'hypnotist',    name: 'Hypnotist',    emoji: '🌀', tag: 'You are getting sleepy',
    text: 'Instead of moving yourself, you may roll and move any other racer that many spaces forward or backward.' },
  { id: 'legion',       name: 'Legion',       emoji: '🛡️', tag: 'We are many', pawns: 2,
    text: 'You race with two pawns. Roll once and split the movement between them however you like. You finish when either pawn crosses the goal.' },
  { id: 'merchant',     name: 'Merchant',     emoji: '💰', tag: 'Cha-ching',
    text: 'Whenever another racer lands on your space, make a sale: you move forward 2.' },
  { id: 'mimic',        name: 'Mimic',        emoji: '🎭', tag: 'Copying the leader',
    text: 'You have the ability of the racer directly ahead of you (the closest racer in front). If nobody is ahead of you, you have no ability.' },
  { id: 'ninja',        name: 'Ninja',        emoji: '🥷', tag: 'Silent but rude',
    text: 'Whenever you pass another racer, that racer moves back 1.' },
  { id: 'priest',       name: 'Priest',       emoji: '⛪', tag: 'Blessed be',
    text: 'Whenever any other racer is moved backward, you move forward 1.' },
  { id: 'restaurateur', name: 'Restaurateur', emoji: '🍜', tag: 'Table for everyone',
    text: 'Any racer that would pass you must stop on your space instead. Everyone\'s hungry.' },
  { id: 'skeleton',     name: 'Skeleton',     emoji: '💀', tag: 'Can\'t kill what\'s dead',
    text: 'You cannot be sent back to Start. Whenever another racer\'s ability moves you, move forward 2 instead.' },
  { id: 'slime',        name: 'Slime',        emoji: '🟢', tag: 'Stuck on you',
    text: 'Any racer that lands on your space gets stuck and skips their next turn.' },
  { id: 'sprinter',     name: 'Sprinter',     emoji: '🏃', tag: 'Built different',
    text: 'Add 1 to every roll.' },
  { id: 'thief',        name: 'Thief',        emoji: '🦝', tag: 'Finders keepers',
    text: 'At the start of your turn, you may use the last roll made by any other player instead of rolling.' },
  { id: 'tortoise',     name: 'Tortoise',     emoji: '🐢', tag: 'Slow and steady',
    text: 'Do not roll. Move exactly 3 every turn. Nothing can move you backward.' },
  { id: 'trickster',    name: 'Trickster',    emoji: '🃏', tag: 'Try that again',
    text: 'Once per turn, you may force any other racer to reroll before they move.' },
  { id: 'vampire',      name: 'Vampire',      emoji: '🧛', tag: 'I vant your spaces',
    text: 'Whenever you land on a space with another racer, drain them: they move back 2 and you move forward 2.' },
  { id: 'wizard',       name: 'Wizard',       emoji: '🧙', tag: 'Roll? What roll?',
    text: 'Once per race, instead of rolling, choose any number from 1 to 6 and move that far.' },
];

// ── Experimental characters — brand new ideas, untested! ─────
const EXPERIMENTAL_CARDS = [
  { id: 'magnet',       name: 'Magnet',       emoji: '🧲', tag: 'Pulling rank',
    text: 'At the start of your turn, the closest racer ahead of you moves back 2. Then roll.' },
  { id: 'timetraveler', name: 'Time Traveler', emoji: '⏳', tag: 'Been here before',
    text: 'Instead of rolling, you may reuse your previous roll from this race.' },
  { id: 'snowball',     name: 'Snowball',     emoji: '❄️', tag: 'Gathering momentum',
    text: 'Add 1 to your roll for each turn you have taken this race without being moved backward (max +4). Reset to 0 if anything moves you back.' },
  { id: 'pigeon',       name: 'Pigeon',       emoji: '🐦', tag: 'Rats with wings',
    text: 'Whenever you roll a 1, take flight: move 7 instead.' },
  { id: 'locksmith',    name: 'Locksmith',    emoji: '🔐', tag: 'Nothing gets through',
    text: 'Racers on your space cannot use their abilities. You can never be made to skip a turn.' },
  { id: 'cartographer', name: 'Cartographer', emoji: '🗺️', tag: 'X marks the spot',
    text: 'At the start of the race, announce a space number. If you ever land on it exactly, move 5 more.' },
  { id: 'weathervane',  name: 'Weathervane',  emoji: '🌬️', tag: 'Which way\'s the wind?',
    text: 'Do not roll. Move the same number as the last roll made by any other player.' },
  { id: 'mule',         name: 'Mule',         emoji: '🫏', tag: 'Beast of burden',
    text: 'Whenever you move, every racer on your space moves with you.' },
  { id: 'balloon',      name: 'Balloon',      emoji: '🎈', tag: 'Full of hot air',
    text: 'Subtract 1 from every roll. Whenever anything would move you backward, float forward that many spaces instead.' },
  { id: 'anchor',       name: 'Anchor',       emoji: '⚓', tag: 'Dead weight',
    text: 'Any racer that passes you moves back 1 at the start of their next turn.' },
  { id: 'echo',         name: 'Echo',         emoji: '🔊', tag: '…echo… echo…',
    text: 'Whenever another racer\'s ability triggers, move 1.' },
  { id: 'understudy',   name: 'Understudy',   emoji: '🎬', tag: 'Waiting in the wings',
    text: 'You have the ability of whichever racer is in last place. If that is you, you have no ability.' },
  { id: 'referee',      name: 'Referee',      emoji: '🦓', tag: 'Play nice',
    text: 'Once per race, cancel any ability as it triggers. When you do, move 2.' },
  { id: 'sleepwalker',  name: 'Sleepwalker',  emoji: '😴', tag: 'Do not wake',
    text: 'Do not roll on your turn. Instead, whenever any other racer rolls a 1 or a 2, you move 3.' },
  { id: 'tailgater',    name: 'Tailgater',    emoji: '🚗', tag: 'Two feet behind',
    text: 'Whenever you end your move on the space directly behind another racer, move onto their space.' },
  { id: 'fisherman',    name: 'Fisherman',    emoji: '🎣', tag: 'Reeling them in',
    text: 'Once per race, instead of rolling, CAST: the racer in the lead moves back 3.' },
  { id: 'lighthouse',   name: 'Lighthouse',   emoji: '🗼', tag: 'Guiding light',
    text: 'At the start of your turn, every racer behind you moves 1. Then roll and add 1 for each racer that moved.' },
  { id: 'bureaucrat',   name: 'Bureaucrat',   emoji: '📋', tag: 'Form 27-B, please',
    text: 'A racer may only pass you if they rolled a 6. Otherwise they stop on the space behind you.' },
  { id: 'conductor',    name: 'Conductor',    emoji: '🎼', tag: 'All together now',
    text: 'When you roll an even number, every other racer also moves 1. When you roll an odd number, you move 1 extra.' },
  { id: 'cloud',        name: 'Cloud',        emoji: '☁️', tag: 'Silver lining',
    text: 'If you are in last place at the start of your turn, move 5 instead of rolling.' },
  { id: 'chameleon',    name: 'Chameleon',    emoji: '🦎', tag: 'Blends right in',
    text: 'At the start of your turn, choose any card that was left undrafted this race. Use its ability this turn.' },
  { id: 'bard',         name: 'Bard',         emoji: '🪕', tag: 'Encore!',
    text: 'Whenever a rival lands on your space, you both move 2.' },
  { id: 'kite',         name: 'Kite',         emoji: '🪁', tag: 'Wound up tight',
    text: 'At the start of your turn, you may move back up to 3 spaces. Add that many to your roll.' },
  { id: 'lumberjack',   name: 'Lumberjack',   emoji: '🪓', tag: 'Timber!',
    text: 'Once per race, instead of rolling, CHOP: every racer ahead of you moves back 2.' },
  { id: 'bubble',       name: 'Bubble',       emoji: '🫧', tag: 'Pop goes the racer',
    text: 'Whenever a rival lands on your space, you pop: move to the space directly behind the leader.' },
  { id: 'portalmage',   name: 'Portal Mage',  emoji: '🚪', tag: 'Mind the gap',
    text: 'Once per race, instead of rolling, swap places with any other racer.' },
  { id: 'weightlifter', name: 'Weightlifter', emoji: '🏋️', tag: 'All or nothing',
    text: 'Odd rolls move you 5. Even rolls move you 1.' },
  { id: 'snail',        name: 'Snail',        emoji: '🐌', tag: 'Slow and slimy',
    text: 'Do not roll. Move 2 every turn. Any rival that passes you must reroll their next roll and take the lower result.' },
  { id: 'firefly',      name: 'Firefly',      emoji: '✨', tag: 'Too bright',
    text: 'Rivals within 2 spaces of you (ahead or behind) subtract 1 from their rolls.' },
  { id: 'scarecrow',    name: 'Scarecrow',    emoji: '🌾', tag: 'Keep off',
    text: 'Rivals cannot land on your space. If they would, they stop 1 space short.' },
  { id: 'rocket',       name: 'Rocket',       emoji: '🚀', tag: 'Three, two, one…',
    text: 'Turn 1: move 8. Turn 2: move 6. Turn 3: move 4. After that, roll normally.' },
  { id: 'ferryman',     name: 'Ferryman',     emoji: '⛵', tag: 'Fare\'s fair',
    text: 'Whenever you move, any rival on your space may choose to ride along with you.' },
  { id: 'gravedigger',  name: 'Gravedigger',  emoji: '⚰️', tag: 'Business is good',
    text: 'Whenever any rival is sent back to Start, you move 3.' },
  { id: 'twins',        name: 'Twins',        emoji: '👯', tag: 'Double trouble', pawns: 2,
    text: 'You race with two pawns. Roll two dice and give one die to each pawn. You finish when either pawn crosses the goal.' },
  { id: 'shapeshifter', name: 'Shapeshifter', emoji: '🦠', tag: 'Who am I today?',
    text: 'At the start of each of your turns, take the ability of the racer directly behind you.' },
  { id: 'puppeteer',    name: 'Puppeteer',    emoji: '🧵', tag: 'Dance, puppets',
    text: 'Once per race, instead of rolling, take a turn for a rival: roll and move them. Then move yourself the same amount.' },
  { id: 'miner',        name: 'Miner',        emoji: '⛏️', tag: 'Struck gold',
    text: 'Whenever you land exactly on a space numbered with a multiple of 5, dig: move 3 more.' },
  { id: 'bee',          name: 'Bee',          emoji: '🐝', tag: 'Bzzz',
    text: 'Whenever you pass a rival, sting: they move back 1. Whenever you land on a rival, they move back 3 and you skip your next turn.' },
  { id: 'seer',         name: 'Seer',         emoji: '🔮', tag: 'I foresaw this',
    text: 'Roll at the END of your turn instead of the start, so everyone can see what you will move next. Add 1 to every roll.' },
  { id: 'landlord',     name: 'Landlord',     emoji: '🏠', tag: 'Rent\'s due',
    text: 'Whenever a rival lands on a space you have already stood on this race, they move back 1 and you move forward 1.' },
  { id: 'blacksmith',   name: 'Blacksmith',   emoji: '⚒️', tag: 'Reforged',
    text: 'Your rolls of 1 count as 4.' },
  { id: 'kangaroo',     name: 'Kangaroo',     emoji: '🦘', tag: 'Boing',
    text: 'Once per turn you may reroll a 1 or a 2. Whenever you land on a rival\'s space, hop 1 space further.' },
  { id: 'marathoner',   name: 'Marathoner',   emoji: '🏅', tag: 'Second wind',
    text: 'From your 4th turn onward, add 2 to every roll.' },
  { id: 'sandman',      name: 'Sandman',      emoji: '🌙', tag: 'Lights out',
    text: 'Whenever you roll a 1, every rival skips their next turn.' },
  { id: 'paparazzo',    name: 'Paparazzo',    emoji: '📸', tag: 'Smile!',
    text: 'Whenever the racer in the lead moves, you move 1.' },
  { id: 'grandma',      name: 'Grandma',      emoji: '👵', tag: 'Mind your manners',
    text: 'Do not roll. Move 3 every turn. Any rival that passes you moves back 1 for being rude.' },
  { id: 'sponge',       name: 'Sponge',       emoji: '🧽', tag: 'Soaks it up',
    text: 'Whenever a rival\'s ability affects you, move 2 after it resolves.' },
  { id: 'auctioneer',   name: 'Auctioneer',   emoji: '🔨', tag: 'Going once…',
    text: 'Start every race on space 3.' },
  { id: 'chessmaster',  name: 'Chessmaster',  emoji: '♟️', tag: 'Three moves ahead',
    text: 'Instead of rolling, you may move exactly 3. If you do, no ability can affect you until your next turn.' },
  { id: 'volcano',      name: 'Volcano',      emoji: '🌋', tag: 'Kaboom',
    text: 'Once per race, instead of rolling, ERUPT: every racer (including you) moves back 3. Then you move 6.' },
  { id: 'gardener',     name: 'Gardener',     emoji: '🌻', tag: 'Room to grow',
    text: 'At the start of your turn, if no rival is within 3 spaces of you, move 2 before rolling.' },
  { id: 'tumbleweed',   name: 'Tumbleweed',   emoji: '🍂', tag: 'Rolling along',
    text: 'Add 1 to your roll for each rival ahead of you.' },
  { id: 'pinball',      name: 'Pinball',      emoji: '🕹️', tag: 'Tilt!',
    text: 'Whenever you land on a rival\'s space, bounce: move again by the same roll.' },
  { id: 'oracle',       name: 'Oracle',       emoji: '🧿', tag: 'Called it',
    text: 'Before rolling, name a number. If your roll matches, move 12 instead.' },
  { id: 'beekeeper',    name: 'Beekeeper',    emoji: '🍯', tag: 'Don\'t touch the hive',
    text: 'Any rival that lands on your space is stung: they move back 4.' },
  { id: 'mailman',      name: 'Mail Carrier', emoji: '📬', tag: 'Special delivery',
    text: 'Whenever a rival rolls a 6, you move 3.' },
  { id: 'diplomat',     name: 'Diplomat',     emoji: '🕊️', tag: 'Immunity',
    text: 'Rivals\' abilities cannot affect you. Subtract 1 from every roll.' },
  { id: 'glacier',      name: 'Glacier',      emoji: '🧊', tag: 'Chill out',
    text: 'Do not roll. Move 1 every turn. Any rival that passes you is frozen: they skip their next turn.' },
  { id: 'detective',    name: 'Detective',    emoji: '🕵️', tag: 'Case closed',
    text: 'Whenever a rival\'s ability triggers, you may roll a die. On a 5 or 6, cancel it.' },
  { id: 'cheerleader',  name: 'Cheerleader',  emoji: '🎀', tag: 'Go team!',
    text: 'At the start of the race, choose a rival. Whenever they roll, you move 1. When they finish, you move 5.' },
  { id: 'yoyo',         name: 'Yo-yo',        emoji: '🪀', tag: 'Up and down',
    text: 'Odd-numbered turns: move double your roll. Even-numbered turns: do not move.' },
  { id: 'cactus',       name: 'Cactus',       emoji: '🌵', tag: 'Prickly',
    text: 'Any rival that lands on your space moves back 2. Rivals cannot move you.' },
  { id: 'locust',       name: 'Locust',       emoji: '🦗', tag: 'Swarm',
    text: 'Whenever you pass a rival, they subtract 1 from their next roll.' },
  { id: 'clockmaker',   name: 'Clockmaker',   emoji: '⏰', tag: 'Right on time',
    text: 'Do not roll. Move a number of spaces equal to the current turn number (turn 1: move 1, turn 2: move 2… max 6).' },
  { id: 'mirror',       name: 'Mirror',       emoji: '🪞', tag: 'Right back at you',
    text: 'Whenever a rival moves you backward, they move backward the same amount.' },
  { id: 'squire',       name: 'Squire',       emoji: '🎠', tag: 'Loyal to a fault',
    text: 'Whenever the racer directly ahead of you moves, you move 1.' },
  { id: 'sculptor',     name: 'Sculptor',     emoji: '🎨', tag: 'Rearranging',
    text: 'Once per race, instead of rolling, swap the positions of any two rivals.' },
  { id: 'escapeartist', name: 'Escape Artist', emoji: '🔗', tag: 'Can\'t hold me',
    text: 'If you start your turn on a space with a rival, move 3 before rolling.' },
  { id: 'slingshot',    name: 'Slingshot',    emoji: '🏹', tag: 'Comeback kid',
    text: 'If you are in last place at the start of your turn, roll two dice and add them together.' },
  { id: 'tightrope',    name: 'Tightrope Walker', emoji: '🎪', tag: 'Don\'t look down',
    text: 'Rolls of 1 or 6 send you back 3. Add 2 to every other roll.' },
  { id: 'dragon',       name: 'Dragon',       emoji: '🐉', tag: 'Scorched earth',
    text: 'Whenever you land on a rival\'s space, breathe fire: that rival and every racer within 1 space of them move back 2.' },
  { id: 'inventor',     name: 'Inventor',     emoji: '🔧', tag: 'Prototype',
    text: 'Once per race, instead of rolling, draw the top card of the deck. You have its ability too for the rest of the race.' },
  { id: 'clown',        name: 'Clown',        emoji: '🤡', tag: 'Honk honk',
    text: 'Whenever you roll the same number as your previous roll, everyone laughs: all rivals move back 2.' },
  { id: 'ostrich',      name: 'Ostrich',      emoji: '🪶', tag: 'Head in the sand',
    text: 'Whenever you roll a 6, dig in: do not move, but nothing can affect you until your next turn. Add 1 to all other rolls.' },
  { id: 'monk',         name: 'Monk',         emoji: '🧘', tag: 'Inner peace',
    text: 'Skip your first turn. Afterward, add 2 to every roll.' },
  { id: 'chef',         name: 'Chef',         emoji: '👨‍🍳', tag: 'Order up',
    text: 'Any rival that passes you gets fed: they move 2 more right away, but their next roll counts as 1.' },
  { id: 'phoenix',      name: 'Phoenix',      emoji: '🔥', tag: 'Rise again',
    text: 'Whenever you are sent back to Start, immediately move 6.' },
  { id: 'hermit',       name: 'Hermit',       emoji: '🐚', tag: 'Leave me alone',
    text: 'If you start your turn with no rival within 2 spaces, add 2 to your roll. Otherwise subtract 1.' },
  { id: 'astronaut',    name: 'Astronaut',    emoji: '👩‍🚀', tag: 'Low gravity',
    text: 'Roll two dice and take the lower one. Move double that number.' },
  { id: 'librarian',    name: 'Librarian',    emoji: '📚', tag: 'Shhh',
    text: 'Rivals on the same space as you cannot use abilities that move other racers.' },
  { id: 'plumber',      name: 'Plumber',      emoji: '🪠', tag: 'Warp pipe',
    text: 'Whenever you land on a space numbered with a multiple of 10, move to the next multiple of 10.' },
  { id: 'werewolf',     name: 'Werewolf',     emoji: '🐺', tag: 'Full moon rising',
    text: 'On even-numbered turns, add 3 to your roll and any rival you land on moves back 3. On odd turns, subtract 1.' },
  { id: 'janitor',      name: 'Janitor',      emoji: '🧹', tag: 'Clean sweep',
    text: 'Whenever you pass a rival, they move back to the space you started this turn on.' },
  { id: 'stuntman',     name: 'Stunt Double', emoji: '🎬', tag: 'Roll camera',
    text: 'When you roll a 6, you may move any rival 6 instead of yourself. If you do, that rival skips their next turn.' },
];

// ── Your own house cards go here (same format) ──────────────
const CUSTOM_CARDS = [
  // { id: 'myracer', name: 'My Racer', emoji: '🦄', tag: 'House rule', text: 'Does something cool.' },
];

// ── Lookup helpers ───────────────────────────────────────────
const CARD_SETS = { official: OFFICIAL_CARDS, experimental: EXPERIMENTAL_CARDS, custom: CUSTOM_CARDS };
const CARD_PALETTE = ['#ff2e88', '#00b4d8', '#ffb703', '#06d6a0', '#ff7b2e', '#8338ec', '#a3d900', '#ef476f', '#118ab2', '#f4a261'];

const CARD_INDEX = {};
Object.entries(CARD_SETS).forEach(([set, list]) => {
  list.forEach((c, i) => {
    CARD_INDEX[c.id] = { ...c, set, number: i + 1, color: CARD_PALETTE[i % CARD_PALETTE.length] };
  });
});

// Cards players make during a "create your own" draft are registered here at runtime.
const RUNTIME_CARDS = {};

function CARD(id) {
  return CARD_INDEX[id] || RUNTIME_CARDS[id] || { id, name: id, emoji: '❓', tag: '', text: 'Unknown card — it may have been removed from cards.js.', set: 'custom', number: 0, color: '#999' };
}
